### ISSUE TITLE
Installing plugin fails

### ISSUE THREAD

**Issue by derBobby** [docker-library/redmine#109]
Hi,

I'm not familiar with ruby and can't get Redmine running with a [Plugin](https://www.redmine.org/plugins/redmine_login_audit). Setup without plugins is fine.

Do you need any further information?

### What I'm using:
redmine:3.4.4
Docker version 17.05.0-ce, build 89658be

### Commands to setup and start Redmine as container
```
useradd -M -s /bin/true redmine

chown -R redmine:redmine $mypath

git clone git@github.com:martin-denizet/redmine_login_audit.git $mypath/plugins/redmine_login_audit

docker run -t --rm \
        -v $mypath/configuration.yml:/usr/src/redmine/config/configuration.yml:ro \
        -v $mypath/files:/usr/src/redmine/files \
        -v $mypath/plugins:/usr/src/redmine/plugins \
        -e REDMINE_DB_MYSQL=x \
        -e REDMINE_DB_USERNAME=x \
        -e REDMINE_DB_PASSWORD=x \
        -e REDMINE_DB_DATABASE=x \
        redmine:3.4.4
```

### Error messages
```
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.0
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.8
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.3
Using loofah 2.2.0
Using rails-html-sanitizer 1.0.3
Using actionview 4.2.8
Using rack 1.6.9
Using rack-test 0.6.3
Using actionpack 4.2.8
Using globalid 0.4.1
Using activejob 4.2.8
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 4.2.8
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.8
Using arel 6.0.4
Using activerecord 4.2.8
Using public_suffix 3.0.2
Using addressable 2.5.2
Using bundler 1.16.1
Using coderay 1.1.2
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching execjs 2.7.0
Installing execjs 2.7.0
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Using thor 0.20.0
Using railties 4.2.8
Fetching coffee-rails 4.2.2
Installing coffee-rails 4.2.2
Using concurrent-ruby 1.0.5
Using css_parser 1.6.0
Using htmlentities 4.3.4
Using jquery-rails 3.1.4
Fetching kaminari 0.17.0
Installing kaminari 0.17.0
Fetching libv8 3.16.14.19 (x86_64-linux)
Installing libv8 3.16.14.19 (x86_64-linux)
Using mimemagic 0.3.2
Using mysql2 0.4.10
Using net-ldap 0.12.1
Using protected_attributes 1.1.4
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using rails 4.2.8
Using rbpdf-font 1.19.1
Using rbpdf 1.19.3
Using redcarpet 3.4.0
Fetching ref 2.0.0
Installing ref 2.0.0
Using request_store 1.0.5
Using rmagick 2.16.0
Using roadie 3.2.2
Using roadie-rails 1.1.1
Fetching therubyracer 0.12.3
Installing therubyracer 0.12.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/therubyracer-0.12.3/ext/v8
/usr/local/bin/ruby -r ./siteconf20180325-8-16gbfdx.rb extconf.rb
checking for -lpthread... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-pthreadlib
        --without-pthreadlib
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:775:in `try_func'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:1002:in `block in have_library'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:997:in `have_library'
        from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.4.0/therubyracer-0.12.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/therubyracer-0.12.3 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.4.0/therubyracer-0.12.3/gem_make.out

An error occurred while installing therubyracer (0.12.3), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.12.3'` succeeds before bundling.

In Gemfile:
  therubyracer
```

**Comment by yosifkit** [comment]
The `redmine` image is currently based on `ruby:2.4-slim` (see [docs](https://github.com/docker-library/docs/tree/b42ce7e4c374e13ce889038c8d2758f71dc9155d/ruby#rubyslim)) so it does not have any tools (ex. `gcc` and `make`) or libraries for compiling native gems. You will need to install any tools that you need in a new image that inherits `FROM redmine:3.4`.
