### ISSUE TITLE
Gantt save to PNG not working

### ISSUE THREAD

**Issue by citiscaner** [docker-library/redmine#132]
I tried to click the PNG in Gantt and I am getting the following error:

Started GET "/projects/kanbanboard_test/issues/gantt.png?month=10&months=6&year=2018&zoom=2" for 10.244.0.0 at 2018-10-11 06:33:45 +0000
Processing by GanttsController#show as PNG
  Parameters: {"month"=>"10", "months"=>"6", "year"=>"2018", "zoom"=>"2", "project_id"=>"kanbanboard_test"}
  Current user: usertest (id=5)
Completed 500 Internal Server Error in 41ms (ActiveRecord: 24.5ms)

Magick::ImageMagickError (non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3265):
  lib/redmine/helpers/gantt.rb:439:in `draw'
  lib/redmine/helpers/gantt.rb:439:in `to_image'
  app/controllers/gantts_controller.rb:42:in `block (2 levels) in show'
  app/controllers/gantts_controller.rb:40:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by tianon** [comment]
Aha, we need to add `gsfonts`! (took some digging into recommends on `imagemagick` with trial and error to find this one)

**Comment by citiscaner** [comment]
I tried installing the gsfonts inside the pod, but i am still getting the same error though.
