### ISSUE TITLE
Unable to upgrade redmine from 3.4.13 to 4

### ISSUE THREAD

**Issue by overraidy** [docker-library/redmine#196]
Hello 
Currently I trying to upgrade my redmine docker container from 3.4.13 to 4 but when I try it, the error below appear

```ruby
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.,
The Gemfile's dependencies are satisfied,
rake aborted!,
NameError: uninitialized constant ActionDispatch::ParamsParser,
/usr/src/redmine/config/application.rb:55:in `<class:Application>',
/usr/src/redmine/config/application.rb:8:in `<module:RedmineApp>',
/usr/src/redmine/config/application.rb:7:in `<top (required)>',
/usr/src/redmine/Rakefile:5:in `<top (required)>',
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>',
(See full trace by running task with --trace),
```

**Comment by wglambert** [comment]
The image only runs `rake db:migrate`, so if that doesn't work to upgrade your database, then that is a question for other redmine users. You might try the [redmine user boards](https://www.redmine.org/projects/redmine/boards). 

These stackoverflow questions look relevant
https://stackoverflow.com/questions/53054925/actiondispatchparamsparser-replacement-after-upgrade-to-rails-5
https://stackoverflow.com/questions/45096629/rails-actiondispatchrequest-parameter-parsers-for-multipart-form-data
