### ISSUE TITLE
When using the docker compose example the container fails with error

### ISSUE THREAD

**Issue by safield** [docker-library/redmine#254]
I am using the stack.yml file described on the docker hub page for redmine. I then use the listed deploy command. I am also running on an Apple M1 Silicon chip.

One the container spins up, it errors out as follows...
```

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.

The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.

The Gemfile's dependencies are satisfied

rake aborted!

Mysql2::Error::ConnectionError: Unknown MySQL server host 'db' (-2)

/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'

/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:118:in `retrieve_connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:90:in `connection'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:172:in `migrate'

/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'

/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Tasks: TOP => db:migrate

(See full trace by running task with --trace)


```

**Comment by safield** [comment]
using the up comand worked...

**Comment by wglambert** [comment]
See https://github.com/docker-library/mysql/issues/778

Mysql upstream doesn't support arm, so you could go with another option like Mariadb, Postgres or SQLite https://github.com/docker-library/docs/tree/master/redmine#redmine_db_mysql-redmine_db_postgres-or-redmine_db_sqlserver "If no variable is set, the image will fall back to using SQLite."
