### ISSUE TITLE
WEBrick doesn't boot correctly?

### ISSUE THREAD

**Issue by CentrixDE** [docker-library/redmine#82]
I was following the Instructions on the official Redmine Docker Page. After running the Redmine Container it's not booting up the HTTP Server. The Logfiles are only updating after i stop the Server(even after 15 Minutes)

Log Files after running the Docker Container:
```console
root@HOSTNAME:~# docker logs redmine
[2017-07-30 23:45:17] INFO  WEBrick 1.3.1
[2017-07-30 23:45:17] INFO  ruby 2.4.1 (2017-03-22) [x86_64-linux]
[2017-07-30 23:45:17] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
```

After i stop the Container the Logfiles are updating to the following:

```console
root@HOSTNAME:~# docker logs redmine                                  
[2017-07-30 23:45:17] INFO  WEBrick 1.3.1                               
[2017-07-30 23:45:17] INFO  ruby 2.4.1 (2017-03-22) [x86_64-linux]      
[2017-07-30 23:45:17] INFO  WEBrick::HTTPServer#start: pid=1 port=3000  
[2017-07-30 23:50:25] INFO  going to shutdown ...                       
[2017-07-30 23:50:25] INFO  WEBrick::HTTPServer#start done.             
=> Booting WEBrick                                                      
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options                       
=> Ctrl-C to shutdown server                                            
Exiting
```

How can i manage to let WEBrick boot?

**Comment by yosifkit** [comment]
When I see that message, I can hit the web server on port 3000. It looks like docker is just printing things in a different order

When I run it interactively, this is what I get: 
```console
$ docker run -it --rm --name red redmine:3.4
... (sqlite database setup/migrate)
=> Booting WEBrick
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2017-07-31 17:17:23] INFO  WEBrick 1.3.1
[2017-07-31 17:17:23] INFO  ruby 2.4.1 (2017-03-22) [x86_64-linux]
[2017-07-31 17:17:23] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
^C[2017-07-31 17:18:42] INFO  going to shutdown ...
[2017-07-31 17:18:43] INFO  WEBrick::HTTPServer#start done.
Exiting
```

Or, without a tty in the container (doing a docker stop in another terminal):
```console 
$ docker run -d --name red redmine:3.4
$ docker logs --follow red
... (sqlite database setup/migrate)
[2017-07-31 17:27:44] INFO  WEBrick 1.3.1
[2017-07-31 17:27:44] INFO  ruby 2.4.1 (2017-03-22) [x86_64-linux]
[2017-07-31 17:27:44] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
[2017-07-31 17:28:20] FATAL SignalException: SIGTERM
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `select'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `block in start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:33:in `start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:158:in `start'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/handler/webrick.rb:34:in `run'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/server.rb:287:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/server.rb:80:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	bin/rails:4:in `require'
	bin/rails:4:in `<main>'
[2017-07-31 17:28:20] INFO  going to shutdown ...
[2017-07-31 17:28:20] INFO  WEBrick::HTTPServer#start done.
=> Booting WEBrick
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
```

**Comment by CentrixDE** [comment]
It seems that my WEBrick isn't booting on my machine because no service is listening on Port 3000 and i also can't connecto to it

**Comment by DeoLeung** [comment]
hit this issue but my `redmine` still works...

**Comment by wglambert** [comment]
Couldn't replicate the issue

```
$ docker run -dp 3000:3000 redmine
e3a5b479040fb0197dd3ef72970cd8d2ec6976d99034bb7b733215f806b41a9f

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
e3a5b479040f        redmine             "/docker-entrypoint.…"   2 seconds ago       Up 1 second         0.0.0.0:3000->3000/tcp   jovial_kilby

$ curl 127.0.0.1:3000
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>Redmine</title>
```

Seems like a usability issue and not one related to an error in the image so I'm going to prune.
If you believe this to be in error then let me know and I'll re-open it
